import './globals.css'
import Nav from './components/nav/main-header'
import { Kanit } from '@next/font/google'

const kanit = Kanit({
  subsets: ['latin'],
  weight: ['400', '700'],
})


export const metadata = {
  title: 'Demo Meal App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={kanit.className}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
